from enum import StrEnum


class EventType(StrEnum):
    USER_CREATED = "USER_CREATED"
    TICKET_CREATED = "TICKET_CREATED"
    TICKET_UPDATED = "TICKET_UPDATED"
    WORK_ORDER_CREATED = "WORK_ORDER_CREATED"
    WORK_ORDER_STARTED = "WORK_ORDER_STARTED"
    WORK_ORDER_FINISHED = "WORK_ORDER_FINISHED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    TRANSACTION_CREATED = "TRANSACTION_CREATED"
    SERVICE_CREATED = "SERVICE_CREATED"
    KNOWLEDGE_ARTICLE_CREATED = "KNOWLEDGE_ARTICLE_CREATED"
